### ISSUE TITLE
About FSDP，deepspeech.

### ISSUE THREAD

**Issue by Alex-Songs** [X-LANCE/SLAM-LLM#101]
Hello，
 May I know if the current FSDP and DeepSpeech are stable and available for use? Do they support multi-machine multi-card and LORA fine-tuning?

**Comment by ddlBoJack** [comment]
Sorry that they are not stable. Anyway Welcome PR :)

**Comment by fclearner** [comment]
fsdp has a bug: sharding_strategy needs “ShardingStrategy” not “str”

**Comment by rookie0607** [comment]
> fsdp 有一个错误：sharding_strategy 需要“ShardingStrategy”而不是“str”

你解决了吗？ @fclearner

**Comment by fclearner** [comment]
> > fsdp 有一个错误：sharding_strategy 需要“ShardingStrategy”而不是“str”
> 
> 你解决了吗？ @fclearner

yes，try this:https://github.com/wenet-e2e/wenet/blob/24375c51c8ccbf1dac0724f5734a6eae4ac9c428/wenet/utils/train_utils.py#L410

**Comment by ddlBoJack** [comment]
https://github.com/X-LANCE/SLAM-LLM/pull/153
