### ISSUE TITLE
The batch decoding results are inconsistent with the non-batch decoding results

### ISSUE THREAD

**Issue by lzl-mt** [X-LANCE/SLAM-LLM#104]
### System Info

torch                         2.0.1
torchaudio                    2.0.2
torchvision                   0.15.2

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### 🐛 Describe the bug

using scripts/decode_hubert_xtralarge_linear_vicuna_7b.sh, decode test-clean
when batchsize=1, decode 50 utts result:
`1089-134686-0000        HE HOPED THERE WOULD BE STEW FOR DINNER TURNIPS AND CARROTS AND BRUISED POTATOES AND FAT MUTTON PIECES TO BE LADLED OUT IN THICK PEPPERED FLOUR FATTENED SAUCE
1089-134686-0001        STUFF IT INTO YOU HIS BELLY COUNSELLED HIM
1089-134686-0002        AFTER EARLY NIGHTFALL THE YELLOW LAMPS WOULD LIGHT UP HERE AND THERE THE SQUALID QUARTER OF THE BROTHELS
1089-134686-0003        HULLO BERTY ANY GOOD IN YOUR MIND
1089-134686-0004        NUMBER TEN FRESH NELLIE IS WAITING ON YOU GOOD NIGHT HUSBAND
1089-134686-0005        THE MUSIC CAME NEARER AND HE RECALLED THE WORDS THE WORDS OF SHELLEY'S FRAGMENT UPON THE MOON WANDERING COMPANIONLESS PALE FOR WEARINESS
1089-134686-0006        THE DULL LIGHT FELL MORE FAINTLY UPON THE PAGE WHEREON ANOTHER EQUATION BEGAN TO UNFOLD ITSELF SLOWLY AND TO SPREAD ABROAD ITS WIDENING TAIL
1089-134686-0007        A COLD LUCID INDIFFERENCE REIGNED IN HIS SOUL
1089-134686-0008        THE CHAOS IN WHICH HIS ARDOUR EXTINGUISHED ITSELF WAS A COLD INDIFFERENT KNOWLEDGE OF HIMSELF
1089-134686-0009        AT MOST BY AN ALMS GIVEN TO A BEGGAR WHOSE BLESSING HE FLED FROM HE MIGHT HOPE WEARILY TO WIN FOR HIMSELF SOME MEASURE OF ACTUAL GRACE
1089-134686-0010        WELL NOW ENNIS I DECLARE YOU HAVE A HEAD AND SO HAS MY STICK
1089-134686-0011        ON SATURDAY MORNINGS WHEN THE SODALITY MET IN THE CHAPEL TO RECITE THE LITTLE OFFICE HIS PLACE WAS A CUSHIONED KNEELING DESK AT THE RIGHT OF THE ALTAR FROM WHICH HE LED HIS WING OF BOYS THROUGH THE RESPONSES
1089-134686-0012        HER EYES SEEMED TO REGARD HIM WITH MILD PITY HER HOLINESS A STRANGE LIGHT GLOWING FAINTLY UPON HER FRAIL FLESH DID NOT HUMILIATE THE SINNER WHO APPROACHED HER
1089-134686-0013        IF EVER HE WAS IMPELLED TO CAST SIN FROM HIM AND TO REPENT THE IMPULSE THAT MOVED HIM WAS THE WISH TO BE HER KNIGHT
1089-134686-0014        HE TRIED TO THINK HOW IT COULD BE
1089-134686-0015        BUT THE DUSK DEEPENING IN THE SCHOOLROOM COVERED OVER HIS THOUGHTS THE BELL RANG
1089-134686-0016        THEN YOU CAN ASK HIM QUESTIONS ON THE CATECHISM DEDALUS
1089-134686-0017        STEPHEN LEANING BACK AND DRAWING IDLY ON HIS SCRIBLER LISTENED TO THE TALK ABOUT HIM WHICH HARREN CHECKED FROM TIME TO TIME BY SAYING
1089-134686-0018        IT WAS STRANGE TOO THAT HE FOUND AN ARID PLEASURE IN FOLLOWING UP TO THE END THE RIGID LINES OF THE DOCTRINES OF THE CHURCH AND PENETRATING INTO OBSCURE SILENCES ONLY TO HEAR AND FEEL THE MORE DEEPLY HIS OWN CONDEMNATION
1089-134686-0019        THE SENTENCE OF SAINT JAMES'S WHICH SAYS THAT HE WHO OFFENDS AGAINST ONE COMMANDMENT BECOMES GUILTY OF ALL HAD SEEMED TO HIM FIRST A SWOLLEN PHRASE UNTIL HE HAD BEGUN TO GROPE IN THE DARKNESS OF HIS OWN STATE
1089-134686-0020        IF A MAN HAD STOLEN A POUND IN HIS YOUTH AND HAD USED THAT POUND TO AMASS A HUGE FORTUNE HOW MUCH WAS HE OBLIGED TO GIVE BACK THE POUND HE HAD STOLEN ONLY OR THE POUND TOGETHER WITH THE COMPOUND INTEREST ACCRUEING UPON IT OR ALL HIS HUGE FORTUNE
1089-134686-0021        IF A LAYMAN IN GIVING BAPTISM POUR THE WATER BEFORE SAYING THE WORDS IS THE CHILD BAPTIZED
1089-134686-0022        HOW COMES IT THAT WHILE THE FIRST BEATITUDE PROMISES THE KINGDOM OF HEAVEN TO THE POOR OF HEART THE SECOND BEATITUDE PROMISES ALSO TO THE MEEK THAT THEY SHALL POSSESS THE LAND
1089-134686-0023        WHY WAS THE SACRAMENT OF THE EUCHARIST INSTITUTED UNDER THE TWO SPECIES OF BREAD AND WINE IF JESUS CHRIST BE PRESENT BODY AND BLOOD SOUL AND DIVINITY IN THE BREAD ALONE AND IN THE WINE ALONE
1089-134686-0024        IF THE WINE CHANGE INTO VINEGAR AND THE HOST CRUMBLE INTO CORRUPTION AFTER THEY HAVE BEEN CONSECRATED IS JESUS CHRIST STILL PRESENT UNDER THEIR SPECIES AS GOD AND AS MAN
1089-134686-0025        A GENTLE KICK FROM THE TALL BOY IN THE BENCH BEHIND URGED STEPHEN TO ASK A DIFFICULT QUESTION
1089-134686-0026        THE RECTOR DID NOT ASK FOR A CATECHISM TO HEAR THE LESSON FROM
1089-134686-0027        HE CLASPED HIS HANDS ON THE DESK AND SAID
1089-134686-0028        THE RETREAT WILL BEGIN ON WEDNESDAY AFTERNOON IN HONOR OF SAINT FRANCIS XAVIER WHOSE FEAST DAY IS SATURDAY
1089-134686-0029        ON FRIDAY CONFESSION WILL BE HEARD ALL THE AFTERNOON AFTER BEADS
1089-134686-0030        BEWARE OF MAKING THAT MISTAKE
1089-134686-0031        STEPHEN'S HEART BEGAN SLOWLY TO FOLD AND FADE WITH FEAR LIKE A WITHERING FLOWER
1089-134686-0032        HE IS CALLED AS YOU KNOW THE APOSTLE OF THE INDIES
1089-134686-0033        A GREAT SAINT SAINT FRANCIS XAVIER
1089-134686-0034        THE RECTOR PAUSED AND THEN SHAKING HIS CLASPED HANDS BEFORE HIM WENT ON
1089-134686-0035        HE HAD THE FAITH IN HIM THAT MOVES MOUNTAINS
1089-134686-0036        A GREAT SAINT SAINT FRANCIS XAVIER
1089-134686-0037        IN THE SILENCE THEIR DARK FIRE KINDLED THE DUSK INTO A TAWNY GLOW
1089-134691-0000        HE COULD WAIT NO LONGER
1089-134691-0001        FOR A FULL HOUR HE HAD PACED UP AND DOWN WAITING BUT HE COULD WAIT NO LONGER
1089-134691-0002        HE SET OFF ABRUPTLY FOR THE BULL WALKING RAPIDLY LEST HIS FATHER'S SHRILL WHISTLE MIGHT CALL HIM BACK AND IN A FEW MOMENTS HE HAD ROUNDED THE CURVE AT THE POLICE BARRACK AND WAS SAFE
1089-134691-0003        THE UNIVERSITY
1089-134691-0004        PRIDE AFTER SATISFACTION UPLIFTED HIM LIKE LONG SLOW WAVES
1089-134691-0005        WHOSE FEET ARE AS THE FEET OF HEARTS AND UNDERNEATH THE EVERLASTING ARMS
1089-134691-0006        THE PRIDE OF THAT DIM IMAGE BROUGHT BACK TO HIS MIND THE DIGNITY OF THE OFFICE HE HAD REFUSED
1089-134691-0007        SOON THE WHOLE BRIDGE WAS TREMBLING AND RESOUNDING
1089-134691-0008        THE UNCOUTH FACES PASSED HIM TWO BY TWO STAINED YELLOW OR RED OR LIVID BY THE SEA AND AS HE STROVE TO LOOK AT THEM WITH EASE AND INDIFFERENCE A FAINT STAIN OF PERSONAL SHAME AND COMMISERATION ROSE TO HIS OWN FACE
1089-134691-0009        ANGRY WITH HIMSELF HE TRIED TO HIDE HIS FACE FROM THEIR EYES BY GAZING DOWN SIDEWAYS INTO THE SHALLOW SWIRLING WATER UNDER THE BRIDGE BUT HE STILL SAW A REFLECTION THEREIN OF THEIR TOP HEAVY SILK HATS AND HUMBLE TAPE LIKE COLLARS AND LOOSELY HANGING CLOTHES BROTHER HICKEY
1089-134691-0010        BROTHER MCARDLE BROTHER KIEFF
1089-134691-0011        THEIR PIETY WOULD BE LIKE THEIR NAMES LIKE THEIR FACES LIKE THEIR CLOTHES AND IT WAS IDLE FOR HIM TO TELL HIMSELF THAT THEIR HUMBLE AND CONTRITE HEARTS IT MIGHT BE PAID A FAR RICHER TRIBUTE OF DEVOTION THAN HIS HAD EVER BEEN A GIFT TENFOLD MORE ACCEPTABLE THAN HIS ELABORATE ADORATION`
WER `1.33%`

When use batchsize=10, result is
`1089-134686-0000        HE HOPED THERE WOULD BE STEW FOR DINNER TURNIPS AND CARROTS AND BRUISED POTATOES AND FAT MUTTON PIECES TO BE LADLED OUT IN THICK PEPPERED FLOUR FATTENED SAUCE
1089-134686-0001        STUFF IT INTO YOU HIS BELLY COUNSELLED HIM
1089-134686-0002        AFTER EARLY NIGHTFALL THE YELLOW LAMPS WOULD LIGHT UP HERE AND THERE THE SQUALID QUARTER OF THE BROTHELS
1089-134686-0003        HULLO BERTY ANY GOOD IN YOUR MIND
1089-134686-0004        NUMBER TEN FRESH NELLIE IS WAITING ON YOU GOOD NIGHT HUSBAND
1089-134686-0005        THE MUSIC CAME NEARER AND HE RECALLED THE WORDS THE WORDS OF SHELLEY'S FRAGMENT UPON THE MOON WANDERING COMPANIONLESS PALE FOR WEARINESS
1089-134686-0006        THE DULL LIGHT FELL MORE FAINTLY UPON THE PAGE WHEREON ANOTHER EQUATION BEGAN TO UNFOLD ITSELF SLOWLY AND TO SPREAD ABROAD ITS WIDENING TAIL
1089-134686-0007        A COLD LUCID INDIFFERENCE REIGNED IN HIS SOUL
1089-134686-0008        THE CHAOS IN WHICH HIS ARDOUR EXTINGUISHED ITSELF WAS A COLD INDIFFERENT KNOWLEDGE OF HIMSELF
1089-134686-0009        AT MOST BY AN ALMS GIVEN TO A BEGGAR WHOSE BLESSING HE FLED FROM HE MIGHT HOPE WEARILY TO WIN FOR HIMSELF SOME MEASURE OF ACTUAL GRACE
1089-134686-0010        WELL NOW ENNIS I DECLARE YOU HAVE A HEAD AND SO HAS MY STICK
1089-134686-0011        ON SATURDAY MORNINGS WHEN THE SODALITY MET IN THE CHAPEL TO RECITE THE LITTLE OFFICE HIS PLACE WAS A CUSHIONED KNEELING DESK AT THE RIGHT OF THE ALTAR FROM WHICH HE LED HIS WING OF BOYS THROUGH THE RESPONSES
1089-134686-0012        HER EYES SEEMED TO REGARD HIM WITH MILD PITY HER HOLINESS A STRANGE LIGHT GLOWING FAINTLY UPON HER FRAIL FLESH DID NOT HUMILIATE THE SINNER WHO APPROACHED HER
1089-134686-0013        IF EVER HE WAS IMPELLED TO CAST SIN FROM HIM AND TO REPENT THE IMPULSE THAT MOVED HIM WAS THE WISH TO BE HER KNIGHT
1089-134686-0014        TRIED TO THINK HOW IT COULD BE
1089-134686-0015        DEEPENING IN THE SCHOOLROOM COVERED OVER HIS THOUGHTS THE BELL RANG
1089-134686-0016        THEN YOU CAN ASK HIM QUESTIONS ON THE CATECHISM DEDALUS
1089-134686-0017        STEPHEN LEANING BACK AND DRAWING IDLY ON HIS SCRIBLER LISTENED TO THE TALK ABOUT HIM WHICH HARREN CHECKED FROM TIME TO TIME BY SAYING
1089-134686-0018        IT WAS STRANGE TOO THAT HE FOUND AN ARID PLEASURE IN FOLLOWING UP TO THE END THE RIGID LINES OF THE DOCTRINES OF THE CHURCH AND PENETRATING INTO OBSCURE SILENCES ONLY TO HEAR AND FEEL THE MORE DEEPLY HIS OWN CONDEMNATION
1089-134686-0019        THE SENTENCE OF SAINT JAMES'S WHICH SAYS THAT HE WHO OFFENDS AGAINST ONE COMMANDMENT BECOMES GUILTY OF ALL HAD SEEMED TO HIM FIRST A SWOLLEN PHRASE UNTIL HE HAD BEGUN TO GROPE IN THE DARKNESS OF HIS OWN STATE
1089-134686-0020        IF A MAN HAD STOLEN A POUND IN HIS YOUTH AND HAD USED THAT POUND TO AMASS A HUGE FORTUNE HOW MUCH WAS HE OBLIGED TO GIVE BACK THE POUND HE HAD STOLEN ONLY OR THE POUND TOGETHER WITH THE COMPOUND INTEREST ACCRUEING UPON IT OR ALL HIS HUGE FORTUNE
1089-134686-0021        IF A LAYMAN IN GIVING BAPTISM POUR THE WATER BEFORE SAYING THE WORDS IS THE CHILD BAPTIZED
1089-134686-0022        HOW COMES IT THAT WHILE THE FIRST BEATITUDE PROMISES THE KINGDOM OF HEAVEN TO THE POOR OF HEART THE SECOND BEATITUDE PROMISES ALSO TO THE MEEK THAT THEY SHALL POSSESS THE LAND
1089-134686-0023        WHY WAS THE SACRAMENT OF THE EUCHARIST INSTITUTED UNDER THE TWO SPECIES OF BREAD AND WINE IF JESUS CHRIST BE PRESENT BODY AND BLOOD SOUL AND DIVINITY IN THE BREAD ALONE AND IN THE WINE ALONE
1089-134686-0024        IF THE WINE CHANGE INTO VINEGAR AND THE HOST CRUMBLE INTO CORRUPTION AFTER THEY HAVE BEEN CONSECRATED IS JESUS CHRIST STILL PRESENT UNDER THEIR SPECIES AS GOD AND AS MAN
1089-134686-0025        GENTLE KICK FROM THE TALL BOY IN THE BENCH BEHIND URGED STEPHEN TO ASK A DIFFICULT QUESTION
1089-134686-0026        THE RECTOR DID NOT ASK FOR A CATECHISM TO HEAR THE LESSON FROM
1089-134686-0027
1089-134686-0028        RETREAT WILL BEGIN ON WEDNESDAY AFTERNOON IN HONOR OF SAINT FRANCIS XAVIER WHOSE FEAST DAY IS SATURDAY
1089-134686-0029        ON FRIDAY CONFESSION WILL BE HEARD ALL THE AFTERNOON AFTER BEADS
1089-134686-0030        BEWARE OF MAKING THAT MISTAKE
1089-134686-0031        STEPHEN'S HEART BEGAN SLOWLY TO FOLD AND FADE WITH FEAR LIKE A WITHERING FLOWER
1089-134686-0032        IS CALLED AS YOU KNOW THE APOSTLE OF THE INDIES
1089-134686-0033        A GREAT SAINT SAINT FRANCIS XAVIER
1089-134686-0034        THE RECTOR PAUSED AND THEN SHAKING HIS CLASPED HANDS BEFORE HIM WENT ON
1089-134686-0035        HE HAD THE FAITH IN HIM THAT MOVES MOUNTAINS
1089-134686-0036        A GREAT SAINT SAINT FRANCIS XAVIER
1089-134686-0037        IN THE SILENCE THEIR DARK FIRE KINDLED THE DUSK INTO A TAWNY GLOW
1089-134691-0000         HE COULD WAIT NO LONGER
1089-134691-0001        FULL HOUR HE HAD PACED UP AND DOWN WAITING BUT HE COULD WAIT NO LONGER
1089-134691-0002        OFF ABRUPTLY FOR THE BULL WALKING RAPIDLY LEST HIS FATHER'S SHRILL WHISTLE MIGHT CALL HIM BACK AND IN A FEW MOMENTS HE HAD ROUNDED THE CURVE AT THE POLICE BARRACK AND WAS SAFE
1089-134691-0003        THE UNIVERSITY
1089-134691-0004        PRIDE AFTER SATISFACTION UPLIFTED HIM LIKE LONG SLOW WAVES
1089-134691-0005        WHOSE FEET ARE AS THE FEET OF HEARTS AND UNDERNEATH THE EVERLASTING ARMS
1089-134691-0006        THE PRIDE OF THAT DIM IMAGE BROUGHT BACK TO HIS MIND THE DIGNITY OF THE OFFICE HE HAD REFUSED
1089-134691-0007        SOON THE WHOLE BRIDGE WAS TREMBLING AND RESOUNDING
1089-134691-0008        UNCOUTH FACES PASSED HIM TWO BY TWO STAINED YELLOW OR RED OR LIVID BY THE SEA AND AS HE STROVE TO LOOK AT THEM WITH EASE AND INDIFFERENCE A FAINT STAIN OF PERSONAL SHAME AND COMMISERATION ROSE TO HIS OWN FACE
1089-134691-0009        ANGRY WITH HIMSELF HE TRIED TO HIDE HIS FACE FROM THEIR EYES BY GAZING DOWN SIDEWAYS INTO THE SHALLOW SWIRLING WATER UNDER THE BRIDGE BUT HE STILL SAW A REFLECTION THEREIN OF THEIR TOP HEAVY SILK HATS AND HUMBLE TAPE LIKE COLLARS AND LOOSELY HANGING CLOTHES BROTHER HICKEY
1089-134691-0010        BROTHER MCARDLE BROTHER KIEFF
1089-134691-0011        THEIR PIETY WOULD BE LIKE THEIR NAMES LIKE THEIR FACES LIKE THEIR CLOTHES AND IT WAS IDLE FOR HIM TO TELL HIMSELF THAT THEIR HUMBLE AND CONTRITE HEARTS IT MIGHT BE PAID A FAR RICHER TRIBUTE OF DEVOTION THAN HIS HAD EVER BEEN A GIFT TENFOLD MORE ACCEPTABLE THAN HIS ELABORATE ADORATION`
WER `3.48%`

### Error logs

same as above

### Expected behavior

None

**Comment by ddlBoJack** [comment]
we will fix this problem very soon.

**Comment by ddlBoJack** [comment]
We have fixed the bug.

**Comment by lzl-mt** [comment]
> We have fixed the bug.

**Comment by lzl-mt** [comment]
Hi, i use this commit "3b620ade1ad2a87a43a4a4f8f2f8a6b6c45fc02c" to decode test-clean, but still get mismatch decoding results, and with some strange symbols like this, and
