### ISSUE TITLE
Request for additional checkpoints of SALM-ASR

### ISSUE THREAD

**Issue by jeeyung** [X-LANCE/SLAM-LLM#108]
Hi! Thank you sharing interesting work!

I would like to ask if you can share additional trained model checkpoints you included in the [paper](https://arxiv.org/pdf/2402.08846).
I would appreciate if you could share SLAM-ASR checkpoints with Whisper ASR encoder, which is included in Table 4 middle rows. 

Thank you!

**Comment by ddlBoJack** [comment]
Sorry that I have finished my internship and I can not reach the servers. The experiment is simple to conduct, just use the ASR script and specify whisper as the encoder. Remember to use whisper encoder's embedding with full 30s.
