### ISSUE TITLE
what's the model's input

### ISSUE THREAD

**Issue by xiayu-cell** [X-LANCE/SLAM-LLM#115]
Hello, I read the dataset, and see the input is the whole audio and one image's ocr result? Did I understand right?

**Comment by ddlBoJack** [comment]
Did you mean the Slidespeech dataset?

**Comment by xiayu-cell** [comment]
yes

**Comment by ddlBoJack** [comment]
Conducting OCR, filtering stop words, and putting into the prompt. Further QA @yanghaha0908

**Comment by xiayu-cell** [comment]
for input，all frame ocr result or one frame ocr result put into prompt？

**Comment by yanghaha0908** [comment]
the whole audio and one image's ocr result, Yes. 
all frame ocr result.

**Comment by xiayu-cell** [comment]
Did you split the audio into parts corresponding to different frame images？If not ，each inference jusy input whole input and one frame image ocr ，what is the output？ whole subtitle or part of whole video？

**Comment by yanghaha0908** [comment]
No. The output is the ASR result of the input speech segment, a part of the whole video.

**Comment by xiayu-cell** [comment]
Could you share how you split the video or audio？

**Comment by yanghaha0908** [comment]
The audio from all videos is segmented using VAD, and the ASR system is then utilized to generate candidate transcripts for each segment. Thus, we obtain the audio/text segments. [1]
[1] SLIDESPEECH: A LARGE SCALE SLIDE-ENRICHED AUDIO-VISUAL CORPUS

**Comment by xiayu-cell** [comment]
Thank you！
