### ISSUE TITLE
BAT: Learning to Reason about Spatial Sounds Pretrained checkpoints

### ISSUE THREAD

**Issue by Utkarsh4430** [X-LANCE/SLAM-LLM#121]
### 🚀 The feature, motivation and pitch

Hi! I liked your work on "BAT: Learning to Reason about Spatial Sounds". However, you have not shared the model pre-trained weights in the repo. When will you be able to share those? Thanks!

**Comment by nicolasperez19** [comment]
Any updates on sharing the model pre-trained weights?

**Comment by ddlBoJack** [comment]
We have updated the checkpoint, please refer to [the recipe](https://github.com/X-LANCE/SLAM-LLM/tree/main/examples/seld_spatialsoundqa).
