### ISSUE TITLE
fp16 configuration for ASR fine-tuning

### ISSUE THREAD

**Issue by yunigma** [X-LANCE/SLAM-LLM#124]
Hello and thank you for the very interesting and useful project.

My colleagues and I are experimenting with different model combinations and fine-tuning with our internal dataset.
The ASR fine-tuning (projector training) works for us but we observe the difference in the performance depending on whether fp16 is set to ```true``` or ```false```.

In the scripts provided in SLAM GitHub, ```fp16``` is set to ```true```. We would like to know whether you used ```fp16=true``` in all your experiments reported in the paper ("An Embarrassingly Simple Approach for LLM with Strong ASR Capacity") and for the checkpoints fine-tuned with LibriSpeech (https://github.com/X-LANCE/SLAM-LLM/tree/main/examples/asr_librispeech#performance-and-checkpoints)? 

In case you tried, did you observe any difference when training with and without ```fp16```?

Thank you!

**Comment by ddlBoJack** [comment]
The `fp16=True` is bound to `AMP`, and it will consume more memory to support AMP. IMO there is not much difference between `fp16=True + AMP` and `fp32`. However, further exploration is needed. Do you have any findings?

**Comment by yunigma** [comment]
Thank you for your reply! We noticed a small difference with and without ```fp16``` and decided to ask about your observations, as we wanted to be consistent with your approach. Yet, it is only on one extra dataset, so as you wrote more exploration is needed.
