### ISSUE TITLE
loss: nan, acc: 0.0

### ISSUE THREAD

**Issue by rookie0607** [X-LANCE/SLAM-LLM#125]
### System Info

none

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### 🐛 Describe the bug

Dear Developer: I'm running the script https://github.com/X-LANCE/SLAM-LLM/blob/main/examples/asr_librispeech/scripts/finetune_whisper_large_linear_vicuna_ 7b.sh, and unlike the original, I replaced LLM with Qwen2-1.5b, and I have a problem with the training, as shown below. `loss: nan, acc: 0.0`
```
[Training Epoch: 2/15, step 486/487 completed (loss: nan, acc: 0.0): 100%|██████████████████████| 487/487 [05:44<00:00,  1.41it/s]
Training Epoch: 2/15, step 486/487 completed (loss: nan, acc: 0.0): 100%|██████████████████████| 487/487 [05:44<00:00,  1.41it/s]
Training Epoch: 2/15, step 486/487 completed (loss: nan, acc: 0.0): 100%|██████████████████████| 487/487 [05:44<00:00,  1.41it/s]
Training Epoch: 2/15, step 486/487 completed (loss: nan, acc: 0.0): 100%|██████████████████████| 487/487 [05:44<00:00,  1.41it/s]]([url](url))
```
 
How can I continue the experiment? @ddlBoJack

### Error logs

1

### Expected behavior

1

**Comment by fclearner** [comment]
是不是某一步突然炸了的。。。

**Comment by rookie0607** [comment]
> 是不是某一步突然炸了的。。。

关掉fp16就好了。。。
测试结果比较差。。

**Comment by fclearner** [comment]
> > 是不是某一步突然炸了的。。。
> 
> 关掉fp16就好了。。。 测试结果比较差。。

加数据

**Comment by yy835055664** [comment]
> > 是不是某一步突然炸了的。。。
> 
> 关掉fp16就好了。。。 测试结果比较差。。

你好，我也遇到这个问题了，但TrainConfig里面的use_fp16默认是False，你说的关掉fp16是指这个嘛？

**Comment by yy835055664** [comment]
> 是不是某一步突然炸了的。。。

你好，我在mala_asr_slidespeech中llm替换成qwen2.5，训练也出现loss:nan，acc:0.3左右；
![image](https://github.com/user-attachments/assets/35627818-53f9-4594-873e-03fa6ed3afdf)
有好的方法解决嘛？

**Comment by fclearner** [comment]
> > 是不是某一步突然炸了的。。。
> 
> 你好，我在mala_asr_slidespeech中llm替换成qwen2.5，训练也出现loss:nan，acc:0.3左右；
> ![image](https://github.com/user-attachments/assets/35627818-53f9-4594-873e-03fa6ed3afdf)
> 有好的方法解决嘛？

因为qwen是用bf16训的，用fp16容易数值溢出，具体可能是某些算子容易数值溢出

**Comment by yy835055664** [comment]
> > > 是不是某一步突然炸了的。。。
> > 
> > 
> > 你好，我在mala_asr_slidespeech中llm替换成qwen2.5，训练也出现loss:nan，acc:0.3左右；
> > ![image](https://private-user-images.githubusercontent.com/57432458/386038684-35627818-53f9-4594-873e-03fa6ed3afdf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1NTczMzAsIm5iZiI6MTczMTU1NzAzMCwicGF0aCI6Ii81NzQzMjQ1OC8zODYwMzg2ODQtMzU2Mjc4MTgtNTNmOS00NTk0LTg3M2UtMDNmYTZlZDNhZmRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE0VDA0MDM1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI4YjkxZjViYjEyMDM3YzRlMTZhOGEzOTZlMTM0N2YzM2U3ODk4MTg5OWY0MjUyNjM5NjRhODk3Y2ZhMmM3YzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.QMHNHWLui-w1m8cCxLkGe6pj5hO2JbDA_S2mpYY5hgQ)
> > 有好的方法解决嘛？
> 
> 因为qwen是用bf16训的，用fp16容易数值溢出，具体可能是某些算子容易数值溢出

多谢，有个问题咨询您一下，尝试llm=llama3-chinese时，训练aishell，测试dev和test，效果都不好：
test:
![image](https://github.com/user-attachments/assets/e982319f-5c59-4c74-885d-a1201386caf2)
dev效果也一样

这种情况您知道怎么解决嘛？

**Comment by fclearner** [comment]
> > > > 是不是某一步突然炸了的。。。
> > > 
> > > 
> > > 你好，我在mala_asr_slidespeech中llm替换成qwen2.5，训练也出现loss:nan，acc:0.3左右；
> > > ![image](https://private-user-images.githubusercontent.com/57432458/386038684-35627818-53f9-4594-873e-03fa6ed3afdf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1NTczMzAsIm5iZiI6MTczMTU1NzAzMCwicGF0aCI6Ii81NzQzMjQ1OC8zODYwMzg2ODQtMzU2Mjc4MTgtNTNmOS00NTk0LTg3M2UtMDNmYTZlZDNhZmRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE0VDA0MDM1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI4YjkxZjViYjEyMDM3YzRlMTZhOGEzOTZlMTM0N2YzM2U3ODk4MTg5OWY0MjUyNjM5NjRhODk3Y2ZhMmM3YzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.QMHNHWLui-w1m8cCxLkGe6pj5hO2JbDA_S2mpYY5hgQ)
> > > 有好的方法解决嘛？
> > 
> > 
> > 因为qwen是用bf16训的，用fp16容易数值溢出，具体可能是某些算子容易数值溢出
> 
> 多谢，有个问题咨询您一下，尝试llm=llama3-chinese时，训练aishell，测试dev和test，效果都不好： test: ![image](https://private-user-images.githubusercontent.com/57432458/386058942-e982319f-5c59-4c74-885d-a1201386caf2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1NjMyMjgsIm5iZiI6MTczMTU2MjkyOCwicGF0aCI6Ii81NzQzMjQ1OC8zODYwNTg5NDItZTk4MjMxOWYtNWM1OS00Yzc0LTg4NWQtYTEyMDEzODZjYWYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE0VDA1NDIwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIyN2FkNTkyYjI5MWU2Y2JiZThjNWQ3ZTlhYzk4ZTc0ODdhNmViN2Y0ODExNmJkN2IzODRiNTlmMmYwNTI2NjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.uv1v1Batbl_IAFqQAyeMHgA0kCk7MOJ7EyqLCQU-3Zs) dev效果也一样
> 
> 这种情况您知道怎么解决嘛？
检查下你的prompt吧，看看是不是eos token有问题

**Comment by yy835055664** [comment]
> > > > > 是不是某一步突然炸了的。。。
> > > > 
> > > > 
> > > > 你好，我在mala_asr_slidespeech中llm替换成qwen2.5，训练也出现loss:nan，acc:0.3左右；
> > > > ![image](https://private-user-images.githubusercontent.com/57432458/386038684-35627818-53f9-4594-873e-03fa6ed3afdf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1NTczMzAsIm5iZiI6MTczMTU1NzAzMCwicGF0aCI6Ii81NzQzMjQ1OC8zODYwMzg2ODQtMzU2Mjc4MTgtNTNmOS00NTk0LTg3M2UtMDNmYTZlZDNhZmRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE0VDA0MDM1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI4YjkxZjViYjEyMDM3YzRlMTZhOGEzOTZlMTM0N2YzM2U3ODk4MTg5OWY0MjUyNjM5NjRhODk3Y2ZhMmM3YzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.QMHNHWLui-w1m8cCxLkGe6pj5hO2JbDA_S2mpYY5hgQ)
> > > > 有好的方法解决嘛？
> > > 
> > > 
> > > 因为qwen是用bf16训的，用fp16容易数值溢出，具体可能是某些算子容易数值溢出
> > 
> > 
> > 多谢，有个问题咨询您一下，尝试llm=llama3-chinese时，训练aishell，测试dev和test，效果都不好： test: ![image](https://private-user-images.githubusercontent.com/57432458/386058942-e982319f-5c59-4c74-885d-a1201386caf2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1NjMyMjgsIm5iZiI6MTczMTU2MjkyOCwicGF0aCI6Ii81NzQzMjQ1OC8zODYwNTg5NDItZTk4MjMxOWYtNWM1OS00Yzc0LTg4NWQtYTEyMDEzODZjYWYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE0VDA1NDIwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIyN2FkNTkyYjI5MWU2Y2JiZThjNWQ3ZTlhYzk4ZTc0ODdhNmViN2Y0ODExNmJkN2IzODRiNTlmMmYwNTI2NjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.uv1v1Batbl_IAFqQAyeMHgA0kCk7MOJ7EyqLCQU-3Zs) dev效果也一样
> > 这种情况您知道怎么解决嘛？
> > 检查下你的prompt吧，看看是不是eos token有问题

prompt使用的默认: "Transcribe speech to text. "
这个是llama3-chinese的pos_token、eos_token
![image](https://github.com/user-attachments/assets/b530119a-4145-40ae-ae0b-9a7086db5804)
是因为prompt原因吗？如果是prompt一般怎么调

**Comment by yy835055664** [comment]
> > > 是不是某一步突然炸了的。。。
> > 
> > 
> > 你好，我在mala_asr_slidespeech中llm替换成qwen2.5，训练也出现loss:nan，acc:0.3左右；
> > ![image](https://private-user-images.githubusercontent.com/57432458/386038684-35627818-53f9-4594-873e-03fa6ed3afdf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE5MDI3MjYsIm5iZiI6MTczMTkwMjQyNiwicGF0aCI6Ii81NzQzMjQ1OC8zODYwMzg2ODQtMzU2Mjc4MTgtNTNmOS00NTk0LTg3M2UtMDNmYTZlZDNhZmRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE4VDA0MDAyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVlYzhlZjNjMWI0NDFmYTdiMDgwZDIwZmRmOTgyYWU2Nzc1MGE3MmQ2OTNlZjZmMDIxMmM2Yzc0Njg4MjMwMjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.nBzjUJAWuyoOmY_mV-mVvAh-93uN6SMd9l2vKiKhpO4)
> > 有好的方法解决嘛？
> 
> 因为qwen是用bf16训的，用fp16容易数值溢出，具体可能是某些算子容易数值溢出

你好，在将use_fp16=false时，训练速度很慢。如果想使用bf16，如何更改？

**Comment by fclearner** [comment]
> > > > 是不是某一步突然炸了的。。。
> > > 
> > > 
> > > 你好，我在mala_asr_slidespeech中llm替换成qwen2.5，训练也出现loss:nan，acc:0.3左右；
> > > ![image](https://private-user-images.githubusercontent.com/57432458/386038684-35627818-53f9-4594-873e-03fa6ed3afdf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE5MDI3MjYsIm5iZiI6MTczMTkwMjQyNiwicGF0aCI6Ii81NzQzMjQ1OC8zODYwMzg2ODQtMzU2Mjc4MTgtNTNmOS00NTk0LTg3M2UtMDNmYTZlZDNhZmRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE4VDA0MDAyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVlYzhlZjNjMWI0NDFmYTdiMDgwZDIwZmRmOTgyYWU2Nzc1MGE3MmQ2OTNlZjZmMDIxMmM2Yzc0Njg4MjMwMjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.nBzjUJAWuyoOmY_mV-mVvAh-93uN6SMd9l2vKiKhpO4)
> > > 有好的方法解决嘛？
> > 
> > 
> > 因为qwen是用bf16训的，用fp16容易数值溢出，具体可能是某些算子容易数值溢出
> 
> 你好，在将use_fp16=false时，训练速度很慢。如果想使用bf16，如何更改？

首先，你的显卡得支持，其次，deepspeed可以设置bf16，然后数据流的tensor type留意下

**Comment by yy835055664** [comment]
> > > > > 是不是某一步突然炸了的。。。
> > > > 
> > > > 
> > > > 你好，我在mala_asr_slidespeech中llm替换成qwen2.5，训练也出现loss:nan，acc:0.3左右；
> > > > ![image](https://private-user-images.githubusercontent.com/57432458/386038684-35627818-53f9-4594-873e-03fa6ed3afdf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE5MDI3MjYsIm5iZiI6MTczMTkwMjQyNiwicGF0aCI6Ii81NzQzMjQ1OC8zODYwMzg2ODQtMzU2Mjc4MTgtNTNmOS00NTk0LTg3M2UtMDNmYTZlZDNhZmRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE4VDA0MDAyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVlYzhlZjNjMWI0NDFmYTdiMDgwZDIwZmRmOTgyYWU2Nzc1MGE3MmQ2OTNlZjZmMDIxMmM2Yzc0Njg4MjMwMjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.nBzjUJAWuyoOmY_mV-mVvAh-93uN6SMd9l2vKiKhpO4)
> > > > 有好的方法解决嘛？
> > > 
> > > 
> > > 因为qwen是用bf16训的，用fp16容易数值溢出，具体可能是某些算子容易数值溢出
> > 
> > 
> > 你好，在将use_fp16=false时，训练速度很慢。如果想使用bf16，如何更改？
> 
> 首先，你的显卡得支持，其次，deepspeed可以设置bf16，然后数据流的tensor type留意下

多谢，如果将use_fp16=false，默认使用什么数据类型进行训练？
