### ISSUE TITLE
[Question] What is the minimum GPU memory requirement for slam_asr?

### ISSUE THREAD

**Issue by world1tree** [X-LANCE/SLAM-LLM#142]
Thank you for your efforts in creating the **SLAM-LLM**. However, I’ve encountered some issues during my use, and I would greatly appreciate your help.

1. I am using whisper-large-v3 + linear projector + llama3-8B and have encountered an OOM issue on a V100 (32GB) GPU. What is the minimum GPU memory needed for this setting(slam_asr)?
2. I have been reducing the model parameters and ultimately found that even a single llama3-8B cannot fit, whereas `llama-factory` can fine-tune llama3-8B on a V100 (32GB). What could be the reason for this (could it be `DDP`)?
3. Additionally, loading llama3-8B using `AutoModelForCausalLM.from_pretrained` took about 9 minutes, but I was able to reduce it to approximately 2 minutes by adding `low_cpu_mem_usage=True`. While I'm unsure of the exact reason, could we consider incorporating this parameter?

**Comment by jindaxz** [comment]
@ddlBoJack Do you have the answer to the second question? I am facing the same issue. Thank you!
