### ISSUE TITLE
Encoder checkpoint in SELD_SpatialSoundQA

### ISSUE THREAD

**Issue by K0145vin** [X-LANCE/SLAM-LLM#143]
Excellent work! However, I noticed that the Encoder checkpoint shared in SELD_SpatialSoundQA is no longer available, and the original SpatialAST weights are incompatible with the current version. Could you please share the pre-trained weights?

**Comment by ddlBoJack** [comment]
We have updated the checkpoint, please refer to [the recipe](https://github.com/X-LANCE/SLAM-LLM/tree/main/examples/seld_spatialsoundqa).
