### ISSUE TITLE
[Question] CTC-ASSISTED LLM-BASED CONTEXTUAL ASR

### ISSUE THREAD

**Issue by hjjjackie** [X-LANCE/SLAM-LLM#178]
Hi, Thank you for sharing the codes. I am wondering how to prepare the following files in `contextual_asr_config.py`?
```
infer_file: str = "/nfs/yangguanrou.ygr/data/fbai-speech/is21_deep_bias/my_ref/test-clean.biasing_100.tsv"
ctc_file: str = "/nfs/yangguanrou.ygr/data/librispeech_my_infer/wavlm_large_libri_test_other_char.txt"
filter_type: str = "char"
phn_to_name_dict: str = "/nfs/yangguanrou.ygr/data/librispeech_my_infer/wavlm_ft_libri960_${ref_split}_phn.json"
```

**Comment by yanghaha0908** [comment]
1. For **infer_file**, get it directly from https://github.com/facebookresearch/fbai-speech/blob/main/is21_deep_bias/ref/test-clean.biasing_100.tsv, I just changed the order to match the audio order.
2. For **ctc_file**, it's the viterbi decode results of our [CTC Fine-tuned WavLM-Large](https://drive.google.com/file/d/12ZmSSbDvx73W0eK1wpUgajapCLhqh5DI/view?usp=drive_link) checkpoint. For your convenience, I will upload them to https://github.com/X-LANCE/SLAM-LLM/tree/main/examples/contextual_asr/scripts/infer.
3. Just ignore **phn_to_name_dict**, it's irrelevant, I'll delete it and update contextual_asr_config.py.
