### ISSUE TITLE
Is it possible to handle speech front-end signal processing tasks?

### ISSUE THREAD

**Issue by zuowanbushiwo** [X-LANCE/SLAM-LLM#88]
### 🚀 The feature, motivation and pitch

like Adaptive noise suppression，Acoustic echo cancellation，Speech Seperation task， thanks！

**Comment by zszheng147** [comment]
We may support these tasks, but perhaps there are already off-the-shelf repos supporting them, like [asteroid](https://github.com/asteroid-team/asteroid).

**Comment by zszheng147** [comment]
Is there any theoretical support for your hypothesis? Could you share it with us? Perhaps you can take a look at our [Spatial Audio Understanding](https://github.com/ddlBoJack/SLAM-LLM/tree/main/examples/seld_spatialsoundqa). We believe LLM can implicitly achieve source separation, but that requires the construction of a finely-tuned dataset.
